# ansible-playbook -i '54.164.134.57,' -u ubuntu edx-east/mongo_3_2.yml -e@test-mongo.yml

##### edx-secure/ansible/vars/edx.yml #####
MONGO_HEARTBEAT_TIMEOUT_SECS: 3
MONGO_STORAGE_ENGINE: 'wiredTiger'
MONGO_STORAGE_ENGINE_OPTIONS:
  wiredTiger:
    engineConfig:
      cacheSizeGB: "{{ (( ansible_memtotal_mb / 1024 ) * 0.70 ) | round(1,'ceil') | int }}" # 70% of available ram - 11GB on m4.xlarge
EDXAPP_MONGO_HOSTS: "{{ MONGO_RS_CONFIG.members|map(attribute='host')|list }}"

##### edx-secure/ansible/vars/stage-edx.yml #####
MONGO_ADMIN_USER: 'admin'
MONGO_ADMIN_PASSWORD: '794jtB7zLIvDjHGu2gD6wKUU'
MONGO_MONITOR_USER: 'cloud-manager'
MONGO_MONITOR_PASSWORD: '7DJ9FTWHJx4TCSPxSmx1k3DD'
MONGO_BACKUP_USER: 'backup'
MONGO_BACKUP_PASSWORD: 'XbJA3LouKV5QDv2NQixnOrQj'
MONGO_CLUSTERED: true
MONGO_REPL_SET: 'jdmulloy-3.2'
mongo_bind_ip: 0.0.0.0
MONGO_RS_CONFIG:
  _id: '{{ MONGO_REPL_SET }}'
  members:
# Must use private IPs here
    - host: '192.168.0.178'

MONGO_CLUSTER_KEY: |
  wW/Cf4woqgbT8e1QzhkO3o/XZVqAv9YeSrVDYxont1rDh2nBAEGB30PhwG9ghtPY
  c1QUc2etVfMnE9vbUhLimU/Xb4j4yLRDurOTi8eYoE8eAvAquLalcz7URMuw8Qt3
  fIyFa3wSXyE04rpsoBrpG53HwwFrN3pra3x4YPs8g77v50V56gfwaStNJ3KPpa5w
  RukdFXnCUPRyONSJEYwjPzI2WucnAZqlDYre6qjxL+6hCjZ4vS/RPgfoHGTUQ62W
  9k2TiWar/c1nL6rZvGhGJHFmZalyL9pJ4SAaYoFPhCmcHusyzjlM8p27AsyJwDyr
  kSI/JPBLMLDoiLUAPHGz1jrGM+iOgTilmfPVy+0UVc9Bf2H4Vs1zKJpUM2RNAPJ7
  S9DzB6q8WtRothbEtwnppWojceid202uLEYCpqhCcH6LR0lTcyJiXCRyHAtue813
  5Djv1m3Z8p2z6B+3ab7CDq+WV9OrBI7+eynnwYGgp4eIHQNNSb1/x/8TeiVMQYyJ
  ONj4PbgVwsdhL+RUuVqCzjK0F4B4FOSSKXbu07L4F/PALqVugH/YebAUAJVo027r
  ca669FSrQ8q6Jgx3M1mCoZkp23CVt3B28+EwpyABh6cwxIrTIvxU6cvxX8M2piz+
  63nKUKoStNhmRA0EGfbY9WRmk1RNlC2jVJAvvJUnNXnouNF2DGV4pRNGlb7yfS+n
  S+3ZZpUDpTLx36CWGPJ1ZpwuZ0p5JPbCSW6gpFZqGFZsQERg6L8Q9FkwESnbfw+V
  oDiVJlClJA2AFXMnAt9q1dhM7OVBj12x9YI5yf1Lw0vVLb7JDmWI7IGaibyxtjFi
  jO4bAEl4RZu3364nFH/nVf6kV2S29pAREMqxbcR5O75OuHFN9cqG7BhYClg+5mWg
  mGKLLgpXsJxd6bMGjxH1uc30E2qbU1mkrW29Ocl5DFuXevK2dxVj71ZiYESIUg87
  KRdC8S3Mljym9ruu4nDC3Sk4xLLuUGp/yD2O0B0dZTfYOJdt

COMMON_MONGO_READ_ONLY_USER: 'read_only'
COMMON_MONGO_READ_ONLY_PASS: "correct horse battery staple"

EDXAPP_MONGO_PASSWORD: 'H8uoZEZJun9BeR5u8mMyA4yh'
EDXAPP_MONGO_USER: 'edxapp003'

FORUM_MONGO_USER: "comments001"
FORUM_MONGO_PASSWORD: "j5fhX0pOwEL1S5WUFZkbZAyZ"

##### edx-secure/ansible/vars/db/edxapp-mongo.yml #####
# This will proxy the configured mongo user/pass/db configured in your
# secure vars file such that it can be used from the mongo_3_0 play to create users.
# That play run might look something like:
# ansible-playbook -i ec2.py mongo_3_0.yml --limit tag_Name_stage-edx-mongo -e@edx.yml -e@stage-edx.yml -e@edxapp-mongo.yml
# You can also add or update users using create_mongo_users.yml
# ansible-playbook -i localhost, create_mongo_users.yml -e@edx.yml -e@stage-edx.yml -e@db/edxapp-mongo.yml

login_host: "{{ EDXAPP_MONGO_HOSTS[1] }}"
repl_set: "{{ EDXAPP_MONGO_REPLICA_SET }}"
MONGO_USERS:
  - user: "{{ EDXAPP_MONGO_USER }}"
    password: "{{ EDXAPP_MONGO_PASSWORD }}"
    database: "{{ EDXAPP_MONGO_DB_NAME }}"
    roles: readWrite
  - user: "{{ COMMON_MONGO_READ_ONLY_USER }}"
    password: "{{ COMMON_MONGO_READ_ONLY_PASS }}"
    database: "{{ EDXAPP_MONGO_DB_NAME }}"
    roles:
      - { db: "{{ EDXAPP_MONGO_DB_NAME }}", role: "read" }
      - { db: "admin",                      role: "clusterMonitor" }
  - user: "{{ MONGO_MONITOR_USER }}"
    password: "{{ MONGO_MONITOR_PASSWORD }}"
    database: "admin"
    roles: clusterMonitor
  - user: "{{ MONGO_BACKUP_USER }}"
    password: "{{ MONGO_BACKUP_PASSWORD }}"
    database: "admin"
    roles: backup

##### edx-internal/ansible/vars/stage-edx.yml #####
EDXAPP_MONGO_DB_NAME: 'jdmulloy-32'
EDXAPP_MONGO_PORT: 27017
EDXAPP_MONGO_REPLICA_SET: 'jdmulloy-3.2'
